name: main

on: [push, pull_request]

jobs:
  linter-and-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10
      - name: Instal poetry
        run: pipx install poetry

      - name: Install dependencies
        run: poetry install

      - name: Run isort
        run: poetry run isort --check .

      - name: Run black
        run: poetry run black --check .

      - name: Run flake8
        run: poetry run flake8 . --exclude=.venv

      - name: Run tests
        run: poetry run pytest .
